### ISSUE TITLE
Review Documentation

### ISSUE THREAD

**Issue by quimpm** [Oriolac/seu#39]
Final Review of the documentation.

**Comment by quimpm** [comment]
- WindFarm Project
   - Project layout
   - Slides final presentation
- Supervision
   - Sequence Diagram Arduino + ChibiOS 
   - Arduino
       - Merge of both codes for Arduino Uno
   - ESP01 Protocol
   - CibiOS
      - Comentar introduccio 
      - Merge
   - Move Chibi to ChibiOS
   - DataProducer1
      - Fritzzing
      - Code Of Dataproducer 1
      - Merge with MQTT
   - DataProducer2
      - Fritzzing
      - Code
      - Merge code with MQTT
      - Delete Wiring with fritzzing in LCD screen
   - ESP 01
      - Delete Humidity sensor section
      - Move LCD to Dataproducer1
    - Mqtt
       - Broker -> Getting Started
       - Fritzzing MQTT Broker
       - Flux Diagram
       - Topics tree

**Comment by sergisi** [comment]
Done:
- Project Layout
- Broker -> Getting started with uMQTTBroker

**Comment by sergisi** [comment]
Doing:
- All the items in Mqtt

**Comment by sergisi** [comment]
Done:
- Fritzing MQTT Broker
- Flux Diagram

**Comment by Oriolac** [comment]
Done: 
* Index nav
* Supervision:
   * ChibiOS
* Move Chibi to ChibiOS

**Comment by quimpm** [comment]
GJ guys, okeeeei lesgoooo
