### ISSUE TITLE
MQTT broker - analysis

### ISSUE THREAD

**Issue by sergisi** [Oriolac/seu#6]

**Comment by Oriolac** [comment]
Mosquitto is an open source broker.
- Mosquitto publisher
- Mosquitto subscriber

**Mosquito publisher cli**
```
mosquitto_pub
-t : topic
-h : address host broker
-p : port
-m : message
-q : QoS
```

It would be nice to have a timestamp at the end of the message to determine the order of the data.

**mosquitto sub**
```
mosquitto_sub
-t : topic
-q : QoS
-t \$SYS\ : whats happening on the broker
-v : protocol version
```

**Comment by Oriolac** [comment]
**Check the CV**
